version: '3.4'

services:

    keycloakdb:
      container_name: keycloakdb
      image: fransmzh/cdd-keycloakdb
      restart: "no"
      environment:
        - POSTGRES_USER=keycloak
        - POSTGRES_PASSWORD=keycloak
        - POSTGRES_DB=keycloakdb
        - TZ=Asia/Jakarta
      expose: 
        - "5433"
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5433:5432'
      volumes: 
        - kcdb:/var/lib/postgresql/data
      networks: 
        - docnet

    keycloak:
      container_name: keycloak
      image: fransmzh/cdd-keycloak
      restart: "no"
      environment:
        - KC_DB=postgres
        - KC_DB_URL=jdbc:postgresql://keycloakdb:5432/keycloakdb
        - KC_DB_USERNAME=keycloak
        - KC_DB_PASSWORD=keycloak
        # - KEYCLOAK_FRONTEND_URL=htpp://keycloak:8080
        # - KEYCLOAK_HTTP_PORT=8080
        # - KEYCLOAK_HOSTNAME=keycloak
        # - HOSTNAME-URL=http://latitude:8180
        # - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled 
      volumes:
        - ./keycloak/import:/opt/keycloak/data/import
      ports:
        - 8180:8080
      # entrypoint: /opt/keycloak/bin/kc.sh start-dev --hostname-url http://keycloak:8080 --hostname-admin-url http://latitude:8180 --import-realm
      entrypoint: /opt/keycloak/bin/kc.sh start-dev --hostname-url http://keycloak:8080 --hostname-strict-backchannel=true
      depends_on:
        - keycloakdb
      networks:
        - docnet

    cdddb:
      container_name: appdb
      image: fransmzh/cdd-appdb
      restart: "no"
      environment:
        - POSTGRES_USER=cdd
        - POSTGRES_PASSWORD=cdd
        - POSTGRES_DB=appdb
        - TZ=Asia/Jakarta
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5435:5432'
      volumes: 
        - appdb:/var/lib/postgresql/data
      networks: 
        - docnet

    discovery:
      container_name: service-discovery
      image: fransmzh/cdd-discovery
      restart: "no"
      expose: 
        - '8761'
      ports:
        - 8761:8761
      networks:
        - docnet

    mockisat:
      container_name: mockisat
      image: fransmzh/cdd-mock-isat
      restart: "no"
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://appdb:5432/appdb 
        - SPRING.DATASOURCE.USERNAME=cdd 
        - SPRING.DATASOURCE.PASSWORD=cdd 
        - SPRING_JPA_HIBERNATE_DDL_AUTO=none
        - SPRING_BOOT_ADMIN_CLIENT_URL=http://discovery:8761/sbadmin
      expose:
        - '9021'
      ports:
        - 9021:9021
      depends_on:
        - cdddb
        - discovery
      networks:
        - docnet

    telco-client:
      container_name: telco-client
      image: fransmzh/cdd-telco-client
      restart: "no"
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://appdb:5432/appdb 
        - SPRING.DATASOURCE.USERNAME=cdd 
        - SPRING.DATASOURCE.PASSWORD=cdd 
        - SPRING_JPA_HIBERNATE_DDL_AUTO=none
        - SPRING_BOOT_ADMIN_CLIENT_URL=http://discovery:8761/sbadmin
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
        - INDOSAT.URL.BASE=http://mockisat:9021/subscribers
        - INDOSAT_URL_ACCESSTOKEN=http://mockisat:9021/oauth2-client/accesstoken
        - EUREKA_INSTANCE_IP_ADDRESS=192.168.0.195
      expose:
        - '9020'
      ports:
        - 9020:9020
      depends_on:
        - cdddb
        - discovery
        - mockisat
      networks:
        - docnet

    mgmt-server:
      container_name: mgmtserver
      image: fransmzh/cdd-mgmt-server
      restart: "no"
      extra_hosts:
        - "host.docker.internal:host-gateway"
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://cdddb:5432/appdb 
        - SPRING.DATASOURCE.USERNAME=cdd 
        - SPRING.DATASOURCE.PASSWORD=cdd 
        - SPRING_JPA_HIBERNATE_DDL_AUTO=none
        - SPRING_BOOT_ADMIN_CLIENT_URL=http://discovery:8761/sbadmin
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
        - EUREKA_INSTANCE_IP_ADDRESS=192.168.0.195
        - KEYCLOAK_BASEURL=http://keycloak:8080
        - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUERURI=http://keycloak:8080/realms/hujanbadai
      ports:
        - 9000:9000
      depends_on:
        - cdddb
        - discovery
        - keycloak
      networks:
        - docnet
        
    middleware:
      container_name: middleware
      image: fransmzh/cdd-middleware
      restart: "no"
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://cdddb:5432/appdb 
        - SPRING.DATASOURCE.USERNAME=cdd 
        - SPRING.DATASOURCE.PASSWORD=cdd 
        - SPRING_JPA_HIBERNATE_DDL_AUTO=create
        - SPRING_BOOT_ADMIN_CLIENT_URL=http://discovery:8761/sbadmin
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
        - EUREKA_INSTANCE_IP_ADDRESS=192.168.0.195
        - APP_TELCO_URL=http://telco-client/telco
        - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI=http://keycloak:8080/realms/hujanbadai
      expose:
        - '9030'
      ports:
        - 9030:9030
      depends_on:
        - cdddb
        - discovery
        - telco-client
        - keycloak
      networks:
        - docnet

volumes:
  appdb: {}
  kcdb: {}

networks: 
  docnet: {}
