version: '3.4'
name: cdd

services:
    cdddb:
      container_name: cdddb
      build: database
      image: postgres:alpine
      restart: "no"
      environment:
        - POSTGRES_USER=cdd
        - POSTGRES_PASSWORD=cdd
        - POSTGRES_DB=cdd-db
        - TZ=Asia/Jakarta
      expose: 
        - "5432"
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5432:5432'
      volumes: 
        - cdddb:/var/lib/postgresql/data
      networks: 
        - docnet

    keycloak:
      container_name: cdd-keycloak
      build: keycloak
      restart: "no"
      environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
      ports:
        - 8180:8080
      depends_on:
        - cdddb
      networks:
        - docnet

    discovery:
      container_name: service-discovery
      build: discovery
      restart: "no"
      expose: 
        - '8761'
      ports:
        - 8761:8761
      networks:
        - docnet

    mockisat:
      container_name: mockisat
      build: mock-isat
      image: fransmzh/cdd-mock-isat
      restart: "no"
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://cdddb:5432/cdd-db 
        - SPRING.DATASOURCE.USERNAME=cdd 
        - SPRING.DATASOURCE.PASSWORD=cdd 
        - SPRING_JPA_HIBERNATE_DDL_AUTO=none
        - SPRING_BOOT_ADMIN_CLIENT_URL=http://discovery:8761/sbadmin
      expose:
        - '9021'
      ports:
        - 9021:9021
      depends_on:
        - cdddb
        - discovery
      networks:
        - docnet

    telco-client:
      container_name: telco-client
      build: telco-client
      image: fransmzh/cdd-telco-client
      restart: "no"
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://cdddb:5432/cdd-db 
        - SPRING.DATASOURCE.USERNAME=cdd 
        - SPRING.DATASOURCE.PASSWORD=cdd 
        - SPRING_JPA_HIBERNATE_DDL_AUTO=none
        - SPRING_BOOT_ADMIN_CLIENT_URL=http://discovery:8761/sbadmin
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
        - INDOSAT.URL.BASE=http://mockisat:9021/subscribers
        - INDOSAT_URL_ACCESSTOKEN=http://mockisat:9021/oauth2-client/accesstoken
        - KEYCLOAK_SERVER-URL=http://keycloak:8180
        - EUREKA_INSTANCE_IP_ADDRESS=192.168.0.195
      expose:
        - '9020'
      ports:
        - 9020:9020
      depends_on:
        - cdddb
        - discovery
        - mockisat
      networks:
        - docnet

volumes:
  cdddb: {}

networks: 
  docnet: {}
