version: '3.4'
name: cdd

services:
    cdd-db:
      container_name: cdd-db
      build: database
      image: postgres:alpine
      restart: "no"
      environment:
        - POSTGRES_USER=cdd
        - POSTGRES_PASSWORD=cdd
        - POSTGRES_DB=cdd-db
        - TZ=Asia/Jakarta
      expose: 
        - "5432"
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5432:5432'
      volumes: 
        - cdddb:/var/lib/postgresql/data
      networks: 
        - docnet

    cdd-keycloak:
      container_name: cdd-keycloak
      build: keycloak
      restart: "no"
      environment:
        - DB_VENDOR= POSTGRES
        - DB_DATABASE= keycloak
        - DB_USER= cdd
        - DB_SCHEMA= public
        - DB_PASSWORD= cdd
        - KEYCLOAK_USER= admin
        - KEYCLOAK_PASSWORD= admin
      ports:
        - 8180:8080
      depends_on:
        - cdd-db

    mock-isat:
      container_name: mock-isat
      build: mock-isat
      restart: "no"
      port:
        - 9021:9021
      depends_on:
        - cdd-db

volumes:
  cdddb: {}

networks: 
  docnet: {}
