version: '3.4'
name: cdd

services:
    cdd-db:
      container_name: cdd-db
      build: database
      image: postgres:alpine
      restart: "no"
      environment:
        - POSTGRES_USER=cdd
        - POSTGRES_PASSWORD=cdd
        - POSTGRES_DB=cdd-db
        - TZ=Asia/Jakarta
      expose: 
        - "5432"
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5432:5432'
      volumes: 
        - cdddb:/var/lib/postgresql/data
      networks: 
        - docnet

    cdd-keycloak:
      container_name: cdd-keycloak
      build: keycloak
      restart: "no"
      environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
      ports:
        - 8180:8080
      depends_on:
        - cdd-db

    discovery:
      container_name: service-discovery
      build: discovery
      restart: "no"
      expose: 
        - '8761'
      ports:
        - 8761:8761

    mock-isat:
      container_name: mock-isat
      build: mock-isat
      restart: "no"
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://cdd-db:5432/cdd-db 
        - SPRING.DATASOURCE.USERNAME=cdd 
        - SPRING.DATASOURCE.PASSWORD=cdd 
        - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      expose:
        - '9001'
      ports:
        - 9021:9021
      depends_on:
        - cdd-db
        - discovery

volumes:
  cdddb: {}

networks: 
  docnet: {}
