version: '3.4'
name: cdd

services:
    cdddb:
      container_name: cdddb
      build: database
      image: postgres:alpine
      restart: "no"
      environment:
        - POSTGRES_USER=cdd
        - POSTGRES_PASSWORD=cdd
        - POSTGRES_DB=cdd-db
        - TZ=Asia/Jakarta
      expose: 
        - "5432"
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5432:5432'
      volumes: 
        - cdddb:/var/lib/postgresql/data
      networks: 
        - docnet

    keycloak:
      container_name: cdd-keycloak
      build: keycloak
      restart: "no"
      environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
      ports:
        - 8180:8080
      depends_on:
        - cdddb
      networks:
        - docnet

    discovery:
      container_name: service-discovery
      build: discovery
      restart: "no"
      expose: 
        - '8761'
      ports:
        - 8761:8761
      networks:
        - docnet

    mock-isat:
      container_name: mock-isat
      build: mock-isat
      restart: "no"
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://cdddb:5432/cdd-db 
        - SPRING.DATASOURCE.USERNAME=cdd 
        - SPRING.DATASOURCE.PASSWORD=cdd 
        - SPRING_JPA_HIBERNATE_DDL_AUTO=none
        - SPRING_BOOT_ADMIN_CLIENT_URL=http://discovery:8761/sbadmin
      expose:
        - '9001'
      ports:
        - 9021:9021
      depends_on:
        - cdddb
        - discovery
      networks:
        - docnet

volumes:
  cdddb: {}

networks: 
  docnet: {}
