GET http://localhost:8900/mgmt/v1/transactions/balance?clientid=AQ66623
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ2WXk1SURhenJVdUUzVmxfUTRMRVd5YWRHaTFITDF2UmxNSURVV1NSSHBJIn0.eyJleHAiOjE2NjY1MjU4NDMsImlhdCI6MTY2NjUyNTU0MywianRpIjoiODhkMjFhNzctOTYxNy00YjhhLThmMWMtNDBmMzc0NzAxODdhIiwiaXNzIjoiaHR0cDovL2xhdGl0dWRlOjgxODAvcmVhbG1zL2h1amFuYmFkYWkiLCJzdWIiOiI4NDFhZTM3YS1lYWI4LTRlNDktOGY3NC03Zjg2YTYyMTJjYjQiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJBUTY2NjIzIiwic2NvcGUiOiJjZGQuYXBpLnIiLCJjbGllbnRJZCI6IkFRNjY2MjMiLCJjbGllbnRIb3N0IjoiMTkyLjE2OC4wLjE5OCIsImNsaWVudEFkZHJlc3MiOiIxOTIuMTY4LjAuMTk4In0.CNTZxi9YDUX3BvsTAKDn6krqEI3KaIQ2qPyw284TfqzwOLdGpPRy7gsrYH2l-OXqCITNtKW3pp7-eZ8pjYm9vgzYKTnmNThP-L_4Q9sV5tl7EEVvDHDSd3d7GI50fezwJ7Fqcavj6D3vwZB3QjKZMUnbyJMR9pKrXQrIejD85C3riva69YHj90rOj2xA4lUfzGllHs2hHVRiZdxGM_hbJYufJ4xYnv_Kp9Oz41QqmW58KrBLIkG4zJwgBi1gRGW-LK1AQP53GHMdzA3JLyXh4iKwHKPYqMeFK0EEr8vsiisG7nmCFftMsjbJSioxkYWYrXdg5LYBhnpi1eSpjecwPA
