POST http://localhost:8900/mgmt/v1/customers/AQ82290/modulset HTTP/1.1
Content-Type: application/json

{
    "modulNames": ["telco:aktivasi","telco:active"]   
}

###
GET  http://localhost:8900/mgmt/v1/customers/AQ82290/modulset HTTP/1.1

###
PUT http://localhost:8900/mgmt/v1/modulset HTTP/1.1
Content-Type: application/json

{
    "modulsetCode": "8206898c-c025-4173-9548-c3a4745f8d8ea",
    "modulNames": ["telco:tenure", ,"telco:expire" ]
}

###

