GET http://localhost:9020/telco/v1/active?msisdn=081112222&refid=2345642
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJCLTdMclg2ZjI1WlpacXoyUEl2VGFPX3JZN2hhUVI0aTJpM0RScEF5S0NRIn0.eyJleHAiOjE2NjYwNjY5ODMsImlhdCI6MTY2NjA2NjY4MywianRpIjoiNjI4NGVkMGYtMmU0OC00MDkxLTgzNjMtYmQ1NjEzODczYTQxIiwiaXNzIjoiaHR0cDovL2xhdGl0dWRlOjgxODAvcmVhbG1zL2h1amFuYmFkYWkiLCJzdWIiOiJmZDFjYjBkYS00YTljLTRlMWUtOTViNS00OTA2YWQzOTk2OGEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJTSUJVMjgzODMiLCJzY29wZSI6ImNkZC5hcGkuciIsImNsaWVudEhvc3QiOiIxOTIuMTY4LjAuMTk4IiwiY2xpZW50SWQiOiJTSUJVMjgzODMiLCJjbGllbnRBZGRyZXNzIjoiMTkyLjE2OC4wLjE5OCJ9.LW4p8D4QGfG72_-jErVApX8w3e47SmYdA8kjTqLsBWHOAKSqqwuROZW0jqltWaLbkJu45dw3XK2x4qEhHK4XjrNNx4ijmxMKoGIBJ4WqHBqcjgpY1RpGHIBYebj5qnGRw4B1xqgykg7bEG2XkEoVv0MrkZjP_cEeu-QVBS7Na-Qe7tPEhjr4CsvMKtJt3QncXodpBEOwSUdqxWxNOGN97a32q91_cRXdNUvx3MfgME2MMvDcfqeDfNi8YM7Vn-bz97SZ-harUTpT5dsW8LIoJY2Yya1HwZCW5y6qiQbob0DuFn_20GaPYU51UHAvzn_ULzv0X9VFBf2M6hap4BRH0w

###
GET http://localhost:9020/telco/v1/suminfo?msisdn=081112222&refid=2345642
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJCLTdMclg2ZjI1WlpacXoyUEl2VGFPX3JZN2hhUVI0aTJpM0RScEF5S0NRIn0.eyJleHAiOjE2NjYwNjY5ODMsImlhdCI6MTY2NjA2NjY4MywianRpIjoiNjI4NGVkMGYtMmU0OC00MDkxLTgzNjMtYmQ1NjEzODczYTQxIiwiaXNzIjoiaHR0cDovL2xhdGl0dWRlOjgxODAvcmVhbG1zL2h1amFuYmFkYWkiLCJzdWIiOiJmZDFjYjBkYS00YTljLTRlMWUtOTViNS00OTA2YWQzOTk2OGEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJTSUJVMjgzODMiLCJzY29wZSI6ImNkZC5hcGkuciIsImNsaWVudEhvc3QiOiIxOTIuMTY4LjAuMTk4IiwiY2xpZW50SWQiOiJTSUJVMjgzODMiLCJjbGllbnRBZGRyZXNzIjoiMTkyLjE2OC4wLjE5OCJ9.LW4p8D4QGfG72_-jErVApX8w3e47SmYdA8kjTqLsBWHOAKSqqwuROZW0jqltWaLbkJu45dw3XK2x4qEhHK4XjrNNx4ijmxMKoGIBJ4WqHBqcjgpY1RpGHIBYebj5qnGRw4B1xqgykg7bEG2XkEoVv0MrkZjP_cEeu-QVBS7Na-Qe7tPEhjr4CsvMKtJt3QncXodpBEOwSUdqxWxNOGN97a32q91_cRXdNUvx3MfgME2MMvDcfqeDfNi8YM7Vn-bz97SZ-harUTpT5dsW8LIoJY2Yya1HwZCW5y6qiQbob0DuFn_20GaPYU51UHAvzn_ULzv0X9VFBf2M6hap4BRH0w



