
GET http://cdd-cloud:9020/telco/v1/api/modulset?msisdn=628567885959&refid=2345642&modulset=telco%3Avalid%20telco%3Aactive%20telco%3Aaktivasi
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ2WXk1SURhenJVdUUzVmxfUTRMRVd5YWRHaTFITDF2UmxNSURVV1NSSHBJIn0.eyJleHAiOjE2NjY1MzM1MjIsImlhdCI6MTY2NjUzMzIyMiwianRpIjoiMDNjYmZjMWItMDhjMS00M2QwLTgwMjEtMGYyNTY1MTViN2FlIiwiaXNzIjoiaHR0cDovL2xhdGl0dWRlOjgxODAvcmVhbG1zL2h1amFuYmFkYWkiLCJzdWIiOiI4NDFhZTM3YS1lYWI4LTRlNDktOGY3NC03Zjg2YTYyMTJjYjQiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJBUTY2NjIzIiwic2NvcGUiOiJjZGQuYXBpLnIiLCJjbGllbnRJZCI6IkFRNjY2MjMiLCJjbGllbnRIb3N0IjoiMTkyLjE2OC4wLjE5OCIsImNsaWVudEFkZHJlc3MiOiIxOTIuMTY4LjAuMTk4In0.WmbpbHBfiY0jfTQ3JloWhi73uMn-CE2QlZYqTeK5tHQCk-ceVoSn2dHpkNlEEjhHgp9yVEbCeJN3MkwWuMS4BCA0K5ApVmRd77FlKyR1Td-PgFd7rYDmjuOOmO5wjHsecF2xnhbw4rmY28qIliGBLCXPOJrv6PC2j8sMXZdear5uAgrvMOAWRjAYAtGNKshIOj6uj10ti5hKCeSigozIvSIi1oAaWNw60LHb6sTwb_aFkxqhZxc5MiCnKHrVe_jqOGYZtkCiPai6dUQdqsh-RKKqzA2ZzLW3GBwBpYuPfEGUTybkpTiFSoUNYjrnrPdq9zrc_t0hqKqPXEW4XJlCPA

###
GET http://localhost:9020/telco/v1/api/modulset?msisdn=081112222&refid=020304&modulset=telco%3Avalid%20telco%3Aactive%20telco%3Aaktivasi
Content-Type: application/json