GET http://localhost:9030/middlewr/v1/api/bundle/cb8b9e5d-f6df-4ef5-a787-4456bf187f67?msisdn=081112222&refid=0249 HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJiWW5oTk5yRF9DM25qc0YzYThtckdkb3RoN1N5YWVxa2h1UHF3akppbWVVIn0.eyJleHAiOjE2NjczMTE1MzQsImlhdCI6MTY2NzMxMDkzNCwianRpIjoiNmExZjlmNTMtZjA3NC00Zjc5LWI5OTgtMjhkZTUyNTQwMDdmIiwiaXNzIjoiaHR0cDovL2xhdGl0dWRlOjgxODAvcmVhbG1zL2dsb3J5ZGF5IiwiYXVkIjpbIjZlYWQ0NGYxLWZmYTAtNDE3NC05MzkxLTAwYzlmNjIwYjhhZSIsIjI5N2EyMDI2LWE1OWMtNDdiOS1iM2VjLTk3ZWFhNTAyMGIzMiJdLCJzdWIiOiJmYjZmMzg3YS1jOTY5LTRjZmMtYTJjMi1iZTI3ZTQzNDY0OTgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJTVUFEMDU3MDYiLCJzY29wZSI6ImNkZC5hcGkuciIsImNsaWVudEhvc3QiOiIxNzIuMTkuMC4xIiwiY2xpZW50SWQiOiJTVUFEMDU3MDYiLCJjbGllbnRBZGRyZXNzIjoiMTcyLjE5LjAuMSJ9.SnLNP6ykoabwChBT8UHc5pkBXog3KUhRn49Ytnux2nb9Bvr-Kj_nBJ1NvLKJ5d-OBn_yBJItFBcInHklD2ZtVu01pn4AW188I7fdScI3Dur4aeYdp5ePU_RBEAHWBdy3Dn_h60J9hU1IiUNGKxbJmEqcZfMxyg-3zarKzaIUbQWdoTaiio64dugCakCk2wf6I4INUXEMAYYAeFF4TrMvFtlMPpjc8YkIB4uBk37obZJId8dEvk77aTybe-FfiMKruioVS9EV-i__odR7cc2N_a3umMWs3IrkqzuaA0Qs6ukToo6SFeimU_k-uWXDUf-gjdPNwlBkiln9CJPbzO6nqQ

###

GET http://localhost:9030/middlewr/v1/api/telco/active?msisdn=081112222&refid=0249 HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJiWW5oTk5yRF9DM25qc0YzYThtckdkb3RoN1N5YWVxa2h1UHF3akppbWVVIn0.eyJleHAiOjE2NjczMTE1MzQsImlhdCI6MTY2NzMxMDkzNCwianRpIjoiNmExZjlmNTMtZjA3NC00Zjc5LWI5OTgtMjhkZTUyNTQwMDdmIiwiaXNzIjoiaHR0cDovL2xhdGl0dWRlOjgxODAvcmVhbG1zL2dsb3J5ZGF5IiwiYXVkIjpbIjZlYWQ0NGYxLWZmYTAtNDE3NC05MzkxLTAwYzlmNjIwYjhhZSIsIjI5N2EyMDI2LWE1OWMtNDdiOS1iM2VjLTk3ZWFhNTAyMGIzMiJdLCJzdWIiOiJmYjZmMzg3YS1jOTY5LTRjZmMtYTJjMi1iZTI3ZTQzNDY0OTgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJTVUFEMDU3MDYiLCJzY29wZSI6ImNkZC5hcGkuciIsImNsaWVudEhvc3QiOiIxNzIuMTkuMC4xIiwiY2xpZW50SWQiOiJTVUFEMDU3MDYiLCJjbGllbnRBZGRyZXNzIjoiMTcyLjE5LjAuMSJ9.SnLNP6ykoabwChBT8UHc5pkBXog3KUhRn49Ytnux2nb9Bvr-Kj_nBJ1NvLKJ5d-OBn_yBJItFBcInHklD2ZtVu01pn4AW188I7fdScI3Dur4aeYdp5ePU_RBEAHWBdy3Dn_h60J9hU1IiUNGKxbJmEqcZfMxyg-3zarKzaIUbQWdoTaiio64dugCakCk2wf6I4INUXEMAYYAeFF4TrMvFtlMPpjc8YkIB4uBk37obZJId8dEvk77aTybe-FfiMKruioVS9EV-i__odR7cc2N_a3umMWs3IrkqzuaA0Qs6ukToo6SFeimU_k-uWXDUf-gjdPNwlBkiln9CJPbzO6nqQ
