POST http://latitude:8180/realms/gloryday/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id=SUAD05706
&client_secret=42yZsDO47VnLnEHFrk9YrxT7Sez6dB7R
&grant_type=client_credentials

###
