POST http://localhost:8900/mgmt/v1/registrations HTTP/1.1
content-type: application/json

{
  "organizationName": "P.T. Adimi Adima Joko",
  "personName": "Gatot Sugiatmo",
  "personPhone": "0831168500",
  "personEmail": "me@fdmazhar.biz",
  "businessRegistrationNumber": "1408962234",
  "taxId": "2411638904"
}