GET http://localhost:8900/mgmt/v1/registrations HTTP/1.1
content-type: application/json
Authorization: Basic dXNlcjphZG1pbg==

###
GET http://localhost:8900/mgmt/v1/registrations/3 HTTP/1.1
content-type: application/json
