GET http://localhost:8900/mgmt/v1/customers/AQ82290
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJnZWdFckpMekJTNVJPS09CY2RYelM3UFh0Y1VHSlJVbW51WTdQMmFGa2cwIn0.eyJleHAiOjE2NjY5NDk2NzMsImlhdCI6MTY2Njk0OTA3MywianRpIjoiYzMzZTU1MmEtNzcxMi00OWI3LThhNGEtYjBiYjU5NWMyNzRmIiwiaXNzIjoiaHR0cDovL2xhdGl0dWRlOjgxODAvcmVhbG1zL2h1amFuYmFkYWkiLCJzdWIiOiJlYTk2M2Q4NS0zMmFmLTQxNTMtOGIxMy02OGQyYmZkMmNhYmMiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJBUTgyMjkwIiwic2NvcGUiOiJjZGQuYXBpLnIiLCJjbGllbnRIb3N0IjoiMTkyLjE2OC4wLjE5OCIsImNsaWVudElkIjoiQVE4MjI5MCIsImNsaWVudEFkZHJlc3MiOiIxOTIuMTY4LjAuMTk4In0.g620_fWpXD68CVfXT8IQgpfR1pG55mfyWlJTZZXZpsMAhLp7nUiwIvkH7sXoIjiEqwe3uO1WOI0xciMAiorKca7lvXvW__vegLcIu6br729dVPBXxOhZqWpQuNoeYSiG3p5WzTU0pgF6F9IIyL4jK8d1wM0vFeLDMa5ZNrcHgKuzAVf8tMpzlYoTcK0XP8UrEpiq3N2NbLbJD3ZIs_5xcm3xMzfR73X4esU5TAjP9E73qOG4QaHrJe_w7u-iCgBZvahZZgJrNwCji7kvMwSU1q194OsJr2foKaHPoOQQf4-1W7WBF_pzHLrTfE75Coewrx5NK0TyCOYxZ_0rLvnzdA
